"""added_profile_pic

Revision ID: 2217fbebcf58
Revises: c152d6bc0b78
Create Date: 2025-04-30 11:57:56.647978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2217fbebcf58'
down_revision = 'c152d6bc0b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))

    # Set 'default_profile_pic.png' as default value
    op.execute("UPDATE \"user\" SET profile_pic = 'default_profile_pic.png' WHERE profile_pic IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_pic', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
