"""adding_user_name

Revision ID: 8ed9c14c1b5a
Revises: c152d6bc0b78
Create Date: 2025-04-29 12:15:45.277100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed9c14c1b5a'
down_revision = 'c152d6bc0b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
